(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Helen, Welcome to Coot version 0.9.5")
(use-graphics-interface-state)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Helen. Welcome to Coot 0.9.5")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 0.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 16.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 0.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
