mabscapefiles = [
'AbWatch.h',
'AbWatch.cpp',
'AntibodyOrderingView.h',
'AntibodyOrderingView.cpp',
'AntigenSetup.h',
'AntigenSetup.cpp',
'AssignChains.h',
'AssignChains.cpp',
'CompetitionSetup.h',
'CompetitionSetup.cpp',
'ContactPoint.h',
'ContactPoint.cpp',
'FiducialSetup.h',
'FiducialSetup.cpp',
'Mab.h',
'Mab.cpp',
'MabscapeWindow.h',
'MabscapeWindow.cpp',
'MabscapeSetup.h',
'MabscapeSetup.cpp',
'Mesh.h',
'Mesh.cpp',
'Playground.h',
'Playground.cpp',
'PosToComp.h',
'PosToComp.cpp',
'Positions.h',
'Positions.cpp',
'PrepWorkView.h',
'PrepWorkView.cpp',
'Symmetry.h',
'Symmetry.cpp',
'main.cpp',
]

executable('mabscape', mabscapefiles,
    link_with : [gui, core],
    link_args: [links],
	include_directories: ['../..'],
    dependencies : gui_deps,
    install: false)

