name: Compile Linux (Ubuntu LTS) with conan

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }} with conan
    if: ${{ !contains(github.event.head_commit.message, '/skip-ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        meson_version: ["1.7.0"]
        ninja_version: ["1.10.2"]
    env:
      # change cache version here to reset cache (if corrupted, e.g.)
      CACHE_V: v0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: rope
          fetch-depth: 0

      - name: Restore source file timestamps for meson caching
        working-directory: rope
        run: |
          git ls-files | while read f; do
            [ -f "$f" ] || continue
            t=$(git log -1 --format="%ct" -- "$f")
            touch -t $(date -d @$t +%Y%m%d%H%M.%S) "$f"
          done

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git build-essential gdb pkg-config

      - name: Install system dependencies (SDL2)
        run: |
          sudo apt-get -y install libsdl2-dev libsdl2-image-dev libglew-dev

      - name: Generate cache keys
        id: get-key
        run: |

          echo "CONAN_KEY=conan-${{ matrix.os }}-${{ env.CACHE_V }}-${{ hashFiles('rope/conanfile.py', 'rope/recipes/**') }}" >> $GITHUB_OUTPUT
          echo "MESON_KEY=meson-${{ matrix.os }}-${{ env.CACHE_V }}-${{ hashFiles('rope/vagabond/**/*.cpp', 'rope/vagabond/**/*.h', 'rope/**/meson.build') }}" >> $GITHUB_OUTPUT

      - name: Restore Conan cache
        id: conan-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.conan2/p
          key: ${{ steps.get-key.outputs.CONAN_KEY }}
          restore-keys: |
            conan-${{ matrix.os }}-${{ env.CACHE_V }}-

      - name: Restore Meson build cache
        id: meson-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: rope/build/ci_build
          key: ${{ steps.get-key.outputs.MESON_KEY }}
          restore-keys: |
            meson-${{ matrix.os }}-${{ env.CACHE_V }}-

      - name: Classify cache result
        run: |
          echo "Conan caches"
          echo "primary: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}"
          echo "matched: ${{ steps.conan-cache-restore.outputs.cache-matched-key }}"

          if [ "${{ steps.conan-cache-restore.outputs.cache-hit }}" = "true" ]; then
          echo "→ exact hit"
          elif [ "${{ steps.conan-cache-restore.outputs.cache-matched-key }}" != "" ]; then
          echo "→ restore-key hit"
          else
          echo "→ full miss"
          fi

          echo "Meson caches"
          echo "primary: ${{ steps.meson-cache-restore.outputs.cache-primary-key }}"
          echo "matched: ${{ steps.meson-cache-restore.outputs.cache-matched-key }}"

          if [ "${{ steps.meson-cache-restore.outputs.cache-hit }}" = "true" ]; then
          echo "→ exact hit"
          elif [ "${{ steps.meson-cache-restore.outputs.cache-matched-key }}" != "" ]; then
          echo "→ restore-key hit"
          else
          echo "→ full miss"
          fi

      - name: Run setup script
        working-directory: rope
        run: setup-scripts/setup.sh --yesman --build=build/ci_build --prefix=$(pwd)/install

      - name: Install RoPE
        working-directory: rope
        run: |
          source build/ci_build/conanbuild.sh
          meson install -C build/ci_build

      - name: Clean build dir
        working-directory: rope/build/ci_build
        run: |
          source conanbuild.sh
          ninja -t cleandead

      - name: Clean stale Conan packages
        run: uvx conan remove "*" --lru=1h -c

      - name: Save Conan cache
        if: ${{ steps.conan-cache-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ~/.conan2/p
          key: ${{ steps.get-key.outputs.CONAN_KEY }}

      - name: Save Meson build cache
        if: ${{ steps.meson-cache-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: rope/build/ci_build
          key: ${{ steps.get-key.outputs.MESON_KEY }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: rope_conan_${{ matrix.os }}_${{ github.sha }}
          path: rope/install/bin/*
          if-no-files-found: error

