name: Compile Linux (Ubuntu LTS) with conan

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }} with conan
    if: ${{ !contains(github.event.head_commit.message, '/skip-ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        meson_version: ["1.7.0"]
        ninja_version: ["1.10.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: rope
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git build-essential gdb pkg-config
          python3 -m pip install meson==${{ matrix.meson_version }} ninja==${{ matrix.ninja_version }} conan
      - name: Install system dependencies (SDL2)
        run: |
          sudo apt-get -y install libsdl2-dev libsdl2-image-dev libglew-dev
      - name: Run setup script
        working-directory: rope
        run: setup-scripts/setup.sh --yesman
